config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :books

  root to: "pages#home"
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  belongs_to :author
  validates :title, presence: true
end

app/models/borrow.rb
class Borrow < ActiveRecord::Base
  belongs_to :book
  belongs_to :reader
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/reader.rb
class Reader < ActiveRecord::Base
  has_many :borrows
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new

  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @book.update(book_params)
    redirect_to book_path(@book)
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private
  # find book id before action
  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:isbn, :title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :isbn %>
  <%= f.input :title %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Editer l'oeuvre</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<%= link_to "Accueil", root_path %> | <%= link_to "Ajouter une oeuvre", new_book_path %>
<h1>Les oeuvres</h1>

<ul>
  <% @books.each do |book| %>
    <li>
      <%= link_to book.title, book_path(book) %>
      <%= book.isbn %>
    </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<%= link_to "Accueil", root_path %> | <%= link_to "Les oeuvres", books_path %>
<h1>Ajouter une oeuvre</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<%= link_to "Accueil", root_path %> | <%= link_to "Les oeuvres", books_path %>
<ul>
  <li>
    <%= @book.title %>
  </li>
</ul>
<%= link_to "Editer", edit_book_path(@book) %> |
<%= link_to "Supprimer", book_path(@book), method: :delete,
data: { confirm: "Êtes-vous sûr?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BiblIo</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/flashes' %>
  <%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1 class="text-center home-title">Bibliothèque du diocèse de Soissons</h1>
<div class="home-bg">
  <div class="home-content">
    <%= link_to "les oeuvres", books_path %>
  </div>
</div>
<p class="text-center home-subtitle">Catherine Liebard, responsable de service, vous accueille à la centrale de 09h à 17h</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>